### ISSUE TITLE
ideas for more advanced filtered search

### ISSUE THREAD

**Issue by ghost** [erfgoed-en-locatie/histograph#28]
As we discussed @bertspaan, it would be great to be able query somewhere in between the current capabilities of the /search and the /sources apis. I.e. request sets of features by filters.

Here's an idea of the kinds of queries we would love to be able to do.
- select concepts based on another concept they have a (hierarchical) relation to. E.g. `/countries/bycontinent/Africa` or `/provinces/bycountry/Netherlands` (how to do multiple countries in the query?)

Or maybe rather like this: `/search?target_type=colony&relation_filter=colonial_ruler&relation_entity=british_empire`
- limit results by exact time and by time period. e.g. `?year=1876` or `&start_year=1876&end_year=1900`.

I think that covers use-cases we're interested in atm.  Am I mentioning anything new here at all?

**Comment by bertspaan** [comment]
@hpfast: I'm sorry for not responding earlier...

First version of filtering by relations works: https://api.histograph.io/search?name=amsterdam&hg:liesIn=drenthe

Documentation will be online, soon. Currently, only searching for `hg:liesIn` paths is possible, other relations will be added too, just like filtering by specific geometries and periods instead of just geometries/periods defined by PITs.

Currently possible: 
- `&hg:liesIn=drenthe`
- `&hg:liesIn=tgn/7003614`

Soon, queries like:
- `&hg:absorbedBy=Gemeente%20Amsterdam`
- `&hg:liesIn=POLYGON(52.3232 5.3 54.32323 5.4)`
- `&hg:periodOverlaps=Deutsche%20Demokratische%20Republik`
- `&hg:periodBefore=1925`

I'm not yet sure what query structure is the best, so if you have ideas, please let me know!

@wires I'm sure you have something to say, too!

**Comment by ghost** [comment]
@bertspaan awesome! This is great. It looks like you're planning/working on quite a wide expansion of the filtering possibilities.

about the query possibilities in general, there are two use-case 'areas' I can imagine:
1. geocode or locate single entity or a small group, exploring a dataset
2. fetch a large set of entities based on a filter, for visualisation

When you're trying to identify or gather more info about a particular PIT and its relatives, you might use relational filters like `hg:absorbedBy`, `hg:liesIn=<hgid>`, `hg:periodOverlaps` and the like.

When you want to make a map/vis of a particular known group of entities at a given time, you might want relation filters like `hg:childOf`, `hg:source=<sourceid>`, `hg:endDate=<year>&hg:endDate=<year>`.

The two overlap each other of course, but what I'm getting at is I think the original use-cases you have in mind are more towards the geocoding side, while I'm also interested in using histograph for visualising larger sets, which tends more towards the second use case area. I.e. when you know what dataset you want to get out of histograph.

Having this kind of API sounds very exciting, though. I hope next week to spend time getting more acquainted with histograph.

**Comment by ghost** [comment]
came across geo_shape types in elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-geo-shape-type.html

relevant to querying and inferencing polygons-with-polygons?

**Comment by bertspaan** [comment]
Work in progress. Issue #49.

**Comment by wires** [comment]
Comment, "select concepts based on another concept they have a (hierarchical) relation to. E.g. /countries/bycontinent/Africa or /provinces/bycountry/Netherlands (how to do multiple countries in the query?)" this used to be very hard / impossible, but we can do now it with equivalence classes https://github.com/graphmalizer/prototype/tree/feat/equivalences
